[default]
DEBUG = false
FLASK_ADMIN_SWATCH = "cerulean" 
APPNAME = "Twitch"
EXTENSIONS = [
    "delivery.ext.db:init_app",
    "delivery.ext.auth:init_app",
    "delivery.ext.admin:init_app",
    "delivery.ext.migrate:init_app",
    "delivery.ext.cli:init_app", 
    "delivery.ext.site:init_app",
]

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///delivery.db"
SQLALCHEMY_TRACK_MODIFICATIONS = false
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
APPNAME = "Twitch Foods (dev)"
EXTENSIONS = [
    "delivery.ext.db:init_app",
    "delivery.ext.auth:init_app",
    "delivery.ext.admin:init_app",
    "delivery.ext.migrate:init_app",
    "delivery.ext.cli:init_app", 
    "delivery.ext.toobar:init_app", 
    "delivery.ext.site:init_app",
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "mysql://...."
